version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # RESTE 3000 INTERNE, MAIS...
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # RESTE 5000 INTERNE
    environment:
      NODE_ENV: production
