services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # ← Dockerfile pour le dev
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5000:5000"  # ← Tu gardes ton port habituel
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
