version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:3000"  # ✅ Coolify va rediriger le domaine vers ce port
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5000"  # ✅ pareil ici pour un sous-domaine propre sans port
    environment:
      NODE_ENV: production
